START TRANSACTION;

DROP TABLE IF EXISTS GAME CASCADE;
DROP TABLE IF EXISTS BOARD CASCADE;

CREATE TABLE IF NOT EXISTS GAME(
    ID INTEGER PRIMARY KEY,
    NUM_TURNS INT NOT NULL DEFAULT 0,
    BOARD_ID INTEGER,
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOARD(
    ID INTEGER PRIMARY KEY,
    WORD TEXT,
    TEAM TEXT, --red, blue, neutral, or assassin
    GUESSED BOOLEAN
);

COMMIT;