import streamlit as st 
import random
import numpy as np

st.title("Codenames")

# GAME BOARD

word_list =  open('wordlist-eng.txt', 'r').readlines()
word_list = [word.strip() for word in word_list]

#For now, we will be playing for the red team and trying to guess the red words
#might have to make another page for GPT as the guesser....

words = random.sample(word_list, 25)

if 'words' not in st.session_state:
    st.session_state.words = words

words_dict = {}
words_dict["blue"] = random.sample(words, 9)
words_dict["red"] = random.sample([w for w in words if (w not in words_dict["blue"])], 9)
words_dict["neutral"] = random.sample([w for w in words if (w not in words_dict["blue"] and w not in words_dict["red"])], 6)
words_dict["assassin"] = random.sample([w for w in words if (w not in words_dict["blue"] and w not in words_dict["red"] and w not in words_dict["neutral"])], 1)

if 'words_dict' not in st.session_state:
    st.session_state.words_dict = words_dict


con_num = 0
cols = st.columns(5)
buttons = []
for i in range(len(cols)):
    with(cols[i]):
        for x in range(5):
                button = st.button(label=st.session_state.words[(i*5 + x)])
                buttons.append(button)

if 'board_cols' not in st.session_state:
    st.session_state.board_cols = cols

if 'board_buttons' not in st.session_state:
     st.session_state.board_buttons = buttons

#st.write(st.session_state)

"""
assassin_word = (st.text_input(label="Enter the assassin word generated by GPT (SPACE SEPARATED)")).split()
neutral_words = (st.text_input(label="Enter the neutral words generated by GPT (SPACE SEPARATED)")).split()
red_words = (st.text_input(label = "Enter the red words generated by GPT (SPACE SEPARATED)")).split()
blue_words = (st.text_input(label = "Enter the blue words generated by GPT (SPACE SEPARATED)")).split()

board = []

def generate_board():
    global board
    board = board + assassin_word + neutral_words + red_words + blue_words
    #print(board)
    random.shuffle(board)
    #print(board)
    board = np.array(board)
    board = np.reshape(board, (5, 5)) #assume board has 25 words
    #print(board)
    cols = st.columns(5)
    for i in range(len(cols)):
        with(cols[i]):
            for x in range(5):
                st.button(label=board[i][x])

generate_board = st.button("Generate board", on_click=generate_board)
"""


#cols = st.columns(5)

#click to guess a word

#maybe move this for loop into generate_board?? + for the labels put the words in the board
"""
for i in range(len(cols)):
    with(cols[i]):
        for x in range(5):
            st.button(label=("word" + str(i) + str(x)))
"""
"""
with cols[0]:
    st.button(label="word")
"""

clue = st.text_input(label="Clue", value="Enter clue here")

