import streamlit as st 
import random
import numpy as np

st.title("Codenames")

# GAME BOARD

#st.write("")

#For now, we will be playing for the red team and trying to guess the red words
#might have to make another page for GPT as the guesser....

assassin_word = (st.text_input(label="Enter the assassin word generated by GPT (SPACE SEPARATED)")).split()
neutral_words = (st.text_input(label="Enter the neutral words generated by GPT (SPACE SEPARATED)")).split()
red_words = (st.text_input(label = "Enter the red words generated by GPT (SPACE SEPARATED)")).split()
blue_words = (st.text_input(label = "Enter the blue words generated by GPT (SPACE SEPARATED)")).split()

board = []

def generate_board():
    global board
    board = board + assassin_word + neutral_words + red_words + blue_words
    #print(board)
    random.shuffle(board)
    #print(board)
    board = np.array(board)
    board = np.reshape(board, (5, 5)) #assume board has 25 words
    print(board)
    cols = st.columns(5)
    for i in range(len(cols)):
        with(cols[i]):
            for x in range(5):
                st.button(label=board[i][x])

generate_board = st.button("Generate board", on_click=generate_board)



#cols = st.columns(5)

#click to guess a word

#maybe move this for loop into generate_board?? + for the labels put the words in the board
"""
for i in range(len(cols)):
    with(cols[i]):
        for x in range(5):
            st.button(label=("word" + str(i) + str(x)))
"""
"""
with cols[0]:
    st.button(label="word")
"""

clue = st.text_input(label="Clue", value="Enter clue here")

